### ISSUE TITLE
大家都没问题么？

### ISSUE THREAD

**Issue by prlei** [firery/mirs-web-vue#19]
ERROR in ./~/_vue-loader@9.9.5@vue-loader/lib/template-compiler.js?id=data-v-58c445dc!./~/_vue-loader@9.9.5@vue-loader/lib/selector.js?type=template&index=0!./src/views/RegisterView.vue
template syntax error tag <mu-flat-button> has no matching end tag.

ERROR in ./~/_vue-loader@9.9.5@vue-loader/lib/template-compiler.js?id=data-v-58c445dc!./~/_vue-loader@9.9.5@vue-loader/lib/selector.js?type=template&index=0!./src/views/RegisterView.vue
template syntax error tag <div> has no matching end tag.

ERROR in ./~/_vue-loader@9.9.5@vue-loader/lib/template-compiler.js?id=data-v-57d254bb!./~/_vue-loader@9.9.5@vue-loader/lib/selector.js?type=template&index=0!./src/views/MovieView.vue
template syntax error tag <div> has no matching end tag.

ERROR in ./~/_vue-loader@9.9.5@vue-loader/lib/template-compiler.js?id=data-v-677636a0!./~/_vue-loader@9.9.5@vue-loader/lib/selector.js?type=template&index=0!./src/views/FriendsView.vue
template syntax error tag <div> has no matching end tag.

----

是在有点改不动了，为啥？改了FriendsView.vue，原因是<div style="margin-top: 15px;" > 结尾少了/，编译器认为缺少上面div的结束。

**Comment by firery** [comment]
原因参加[这里](https://github.com/firery/mirs-web-vue/issues/20)
